{
 "title": "Linux Overview With Open-Falcon",
 "description": "Linux Overview With Open-Falcon，\r\nMetrics Include\r\n- Cpu \r\n- Load \r\n- Memory \r\n- Disk \r\n- Network \r\n- Fd",
 "tags": [ "open-falcon" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "集群", "query": ".*" },
   { "name": "hosts", "label": "主机", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "CPU监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu.idle",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "target": "$hosts#cpu#idle" }
     ]
    },
    {
     "title": "cpu.user",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "target": "$hosts#cpu#user" }
     ]
    },
    {
     "title": "cpu.iowait",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      { "target": "$hosts#cpu#iowait" }
     ]
    },
    {
     "title": "cpu.system",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      { "target": "$hosts#cpu#system" }
     ]
    }
   ]
  },
  {
   "title": "负载监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "负载监控",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "target": "$hosts#load.1min" },
      { "target": "$hosts#load.5min" },
      { "target": "$hosts#load.15min" }
     ]
    }
   ]
  },
  {
   "title": "内存监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem.memused.percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      { "target": "$hosts#mem#memused#percent" }
     ]
    }
   ]
  },
  {
   "title": "磁盘监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "df.bytes.used.percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      { "target": "$hosts#df#bytes#used#percent" }
     ]
    },
    {
     "title": "df.inodes.used.percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      { "target": "$hosts#df#inodes#used#percent" }
     ]
    },
    {
     "title": "disk.io.write_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "target": "$hosts#disk#io#write_bytes" }
     ]
    },
    {
     "title": "disk.io.read_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      { "target": "$hosts#disk#io#read_bytes" }
     ]
    }
   ]
  },
  {
   "title": "网卡监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "net.if.in.bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "target": "$hosts#net#if#in#bytes" }
     ]
    },
    {
     "title": "net.if.out.bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      { "target": "$hosts#net#if#out#bytes" }
     ]
    },
    {
     "title": "net.if.total.bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "target": "$hosts#net#if#total#bytes" }
     ]
    },
    {
     "title": "net.if.total.errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      { "target": "$hosts#net#if#total#errors" }
     ]
    },
    {
     "title": "net.if.total.dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      { "target": "$hosts#net#if#total#dropped" }
     ]
    }
   ]
  },
  { "title": "文件句柄监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "kernel.files.allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "target": "$hosts#kernel#files#allocated" }
   ]
  },
  {
   "title": "kernel.maxfiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "target": "$hosts#kernel#maxfiles" }
   ]
  },
  {
   "title": "kernel.maxproc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "target": "$hosts#kernel#maxproc" }
   ]
  }
 ]
}